const Parties = [
  {
    id: 1,
    name: "BJP",
    text: "Bharatiya Janata Party – “Sabka Saath, Sabka Vikas”",
    symbol: "/images/BJP_Symbol.png",
    type: "National",
    link: "https://www.bjp.org",
  },
  {
    id: 2,
    name: "INC",
    text: "Indian National Congress – “Ab Hoga Nyay”",
    symbol: "/images/INC_Symbol.png",
    type: "National",
    link: "https://www.inc.in",
  },
  {
    id: 3,
    name: "AAP",
    text: "Aam Aadmi Party – “Common Man's Party”",
    symbol: "/images/aap_symbol.png",
    type: "National",
    link: "https://www.aamaadmiparty.org",
  },
  {
    id: 4,
    name: "BSP",
    text: "Bahujan Samaj Party – “Bahujan Hitai, Bahujan Sukhai”",
    symbol: "/images/BSP_Symbol.png",
    type: "National",
    link: "http://www.bspindia.org",
  },
  {
    id: 5,
    name: "CPI(M)",
    text: "Communist Party of India(Marxist) – “Struggle for the People and Serve the People.”",
    symbol: "/images/CPI_Symbol.png",
    type: "National",
    link: "https://www.cpim.org",
  },
  {
    id: 6,
    name: "NPP",
    text: "National People's Party – “One Voice, One Northeast.”",
    symbol: "/images/NPP_Symbol.png",
    type: "National",
    link: "https://www.nppindia.in",
  },
  {
    id: 7,
    name: "AIADMK",
    text: "All India Anna Dravida Munnetra Kazhagam – “Duty, Dignity, Discipline”",
    symbol: "/images/AIADMK_Symbol.png",
    type: "State",
    link: "http://aiadmk.org.in/",
  },
  {
    id: 8,
    name: "AIFB",
    text: "All India Forward Bloc – “Unity and Discipline”",
    symbol: "/images/AIFB_Symbol.png",
    type: "State",
    link: "https://allindiaforwardbloc.org/",
  },
  {
    id: 9,
    name: "AIMIM",
    text: "All India Majlis-e-Ittehadul Muslimeen – “Empowerment and Justice for Minorities”",
    symbol: "/images/AIMIM_Symbol.png",
    type: "State",
    link: "https://www.aimim.org/",
  },
  {
    id: 10,
    name: "AINRC",
    text: "All India N.R. Congress – “Simplicity, Fairness, and Transparency”",
    symbol: "/images/AINRC_Symbol.png",
    type: "State",
    link: null, // Official website not available
  },
  {
    id: 11,
    name: "AIUDF",
    text: "All India United Democratic Front – “Justice and Development for All”",
    symbol: "/images/AIUDF_Symbol.png",
    type: "State",
    link: null,
  },
  {
    id: 12,
    name: "AGP",
    text: "Asom Gana Parishad – “Regionalism and Development”",
    symbol: "/images/AGP_Symbol.jpg",
    type: "State",
    link: "http://www.asomganaparishad.in",
  },
  {
    id: 13,
    name: "BJD",
    text: "Biju Janata Dal – “Peace, Progress, and Prosperity”",
    symbol: "/images/BJD_Symbol.svg",
    type: "State",
    link: "http://www.bjdodisha.org.in",
  },
  {
    id: 14,
    name: "BPF",
    text: "Bodoland People's Front – “Unity, Peace, and Development”",
    symbol: "/images/BPF_Symbol.png",
    type: "State",
    link: null, // Official website not available
  },
  {
    id: 15,
    name: "DMDK",
    text: "Desiya Murpokku Dravida Kazhagam – “Save Mother Tamil and Learn All Languages”",
    symbol: "/images/DMDK_Symbol.png",
    type: "State",
    link: "http://www.dmdkparty.com",
  },
  {
    id: 16,
    name: "DMK",
    text: "Dravida Munnetra Kazhagam – “Upliftment of Dravidians ”",
    symbol: "/images/DMK_Symbol.png",
    type: "State",
    link: "http://www.dmk.in",
  },
  {
    id: 17,
    name: "GFP",
    text: "Goa Forward Party – “Goem, Goenkar, Goenkarponn”",
    symbol: "/images/GFP_Symbol.png",
    type: "State",
    link: "http://www.goaforwardparty.org",
  },
  {
    id: 18,
    name: "HSPDP",
    text: "Hill State People's Democratic Party – “For the Cause of the Hill People”",
    symbol: "/images/HSPDP_Symbol.svg",
    type: "State",
    link: null, // Official website not available
  },
  {
    id: 19,
    name: "IUML",
    text: "Indian Union Muslim League – “Protection of Minority Rights and Secularism”",
    symbol: "/images/IUML_Symbol.png",
    type: "State",
    link: "http://www.iuml.com",
  },
  {
    id: 20,
    name: "IPFT",
    text: "Indigenous People's Front of Tripura – “Rights and Development”",
    symbol: "/images/IPFT_Symbol.webp",
    type: "State",
    link: null, // Official website not available
  },
  {
    id: 21,
    name: "JKNC",
    text: "Jammu and Kashmir National Conference – “Peace, Progress, and Autonomy for J&K”",
    symbol: "/images/JKNC_Symbol.png",
    type: "State",
    link: "http://www.jknc.in",
  },
  
  
  {
    id: 34,
    name: "RJD",
    text: "Rashtriya Janata Dal – “Social Justice and Secularism”",
    symbol: "/images/RJD_Symbol.jpg",
    type: "State",
    link: "http://www.rjd.co.in",
  },
];

export default Parties;